language: python
python: '3.6'

install:
  # Install requirements
  - pip install ansible
  - pip install ansible-lint
  - pip install molecule

  # Check ansible version
  - ansible --version

script:
- ansible-lint main.yml 
