language: python
python: '3.8'

install:
  # Install requirements
  - pip install ansible
  - pip install ansible-lint
  - pip install molecule

  # Check ansible version
  - ansible --version

script:
- ansible-lint main.yml -x 206 -x 508 -v
