- name: Create user
  user:
    name: vmuser
    state: present
    shell: /bin/bash
    password: "{{ 'Password1' | password_hash('sha512') }}"
    update_password: on_create
  tags: [initialize, create_user]