- name: Edit Sshd Config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    insertafter: '#PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: restart_sshd
  tags: [initialize, sshd]