---
- name: Check old versions of Docker not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent
    
- name: Creating a docker repository
  yum_repository:
    description: repo for docker
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
    gpgcheck: no

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: Restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install pip"
  package: 
    name: "python3-pip"
    state: present
    update_cache: true
    
- name: "Install Docker SDK"
  pip:
    name: "docker"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"