- name: "Update docker service"
  replace:
    path: "/lib/systemd/system/docker.service"
    regexp: "^ExecStart.*"
    replace: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376 --tlsverify --tlscacert={{ certificate_folder }}/ca.pem --tlscert={{ certificate_folder }}/server_cert.pem --tlskey={{ certificate_folder }}/server_key.pem"
  notify: 
    - "Reload Daemon"
    - "Stop Docker Service"
    - "Stop Docker Socket"
    - "Reload Daemon"
    - "Start Docker"