---
# tasks file for docker
- name: Create Docker Disk
  include_tasks: docker-disk.yml

- name: Install Docker CE 
  include_tasks: docker-centos.yml

- name: Include gen-certs.yml
  include: gen-certs.yml
  tags: [common, certs]

- name: Docker Daemon
  include_tasks: docker-daemon.yml

- name: Add Docker User
  include_tasks: docker-users.yml
  when: docker_users | length > 0

